[project]
name = "deepseek-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "pydantic>=2.10.5",
    "vllm>=0.6.6",
]

[dependency-groups]
dev = [
    "ruff>=0.9.2",
]
